# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TestCase123.
      - MYSQL_DATABASE=basic
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 127.0.0.1:3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

#command: sleep infinity

# Allows accessing dbs through the port forwardings. dev container behaves like host for networking
#network_mode: host
