---
title: "Fuzzywuzzy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(RMariaDB)
library(DBI)
library(bcputility)
library(tm)
library(dplyr)
library(stringr)
```


```{r}
#DB Set up 
con <- dbConnect(RMariaDB::MariaDB(), username="root", password="TestCase123.", dbname ="basic", host="localhost")
dbListTables(con)
```

```{r}
df <- dbReadTable(con, "Rectified_Total")
```
```{r}
new_df <- data.frame( doc_id = 1:nrow(df), text =df$Job_Description )

```


```{r}
df$sla80
```




```{r}
(ds <- DataframeSource(new_df))
x <- VCorpus(ds)

```
```{r}
writeCorpus(x, path = "./Vcorpus")
```

```{r}
x <- Corpus(DirSource("./corpus"), readerControl = list(language="lat"))
```
Start Here if you are pulling from git

```{r}
x <- loadcorpus(files = "all", corpus.dir = "./corpus", encoding = "UTF-8")
```

```{r}
inspect(x[1:2])
```
```{r}
x <- tm_map(x, content_transformer(tolower))
x <- tm_map(x, removeWords, stopwords("english"))
```

```{r}
inspect(x[1:2])
```


```{r}
dtm <- DocumentTermMatrix(x)
```

```{r}
inspect(dtm)
```

```{r}
findAssocs(dtm, "data", 0.40)
```

```{r}
url.data <- "https://raw.githubusercontent.com/jamhall/programming-languages-csv/master/languages.csv"
raw <- read.csv(url(url.data), header = TRUE,)
programming_list <- tolower(raw$name)
```


```{r}
programming_list_dtm <- DocumentTermMatrix(x, list(dictionary = c(programming_list)))
```
```{r}
library(tidytext)
```



```{r}
programming_list_df <- as.data.frame(as.matrix(programming_list_dtm), stringsAsFactors=False)
```

```{r}
Programming_Skills = new
```

<H1> Let Get Counts </H1>

```{r}
sum(programming_list_df$python != 0, na.rm=TRUE)
```
<H1> Now Let's Iterate </H1>

```{r}
index_df <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(index_df) <-c("Skill", "Count")

```

```{r, cache=TRUE}
list_holder <- list()
for(i in 1:ncol(programming_list_df)) {       # for-loop over columns
  index_df[i,] <- c(colnames(programming_list_df)[i], (sum(programming_list_df[, i] != 0, na.rm=TRUE)))
}
index_df
```
```{r}
index_df <- index_df[index_df$Count != 0, ]
```

```{r}
list_test <- findAssocs(dtm, "data", 0.40)
list_test
```
```{r}
list_test
test_me_123 <- (unlist(list_test))
test_me_123
test_me_1234 <- str_remove(names(unlist(list_test)), "data.")
test_me_1234
```

```{r}
index_df$Skill[1,]
```


```{r}
index_df$Asociations = "None" 
for(i in 1:nrow(index_df)) {
    associations <-  findAssocs(dtm, index_df$Skill[i], 0.40)
    if (!is.null(associations)) {
      if(!is.null(names(unlist(associations)))){
        if (!is.null(dataWordList)){
          index_df[i, index_df$Asociations] = str_remove(names(unlist(associations)), "data.")
        }
      }
  }
}
```
```{r}
index_df[2]
```



```{r}
head(colnames(programming_list_df)[5])
programming_list_df.colindex.names[2]
```


```{r}
print(list_holder)
```



```{r, cache=TRUE}
tail(DF)
```
```{r}
library(e1071)
```

```{r}
dat = data.frame(x, y = as.factor(y))
svmfit = svm(y ~ ., data = dat, kernel = "linear", cost = 10, scale = FALSE)
```

